version: '3'

services:

################################################################################
# PostgreSQL
################################################################################

    db:
        image: postgres:9.6
        environment:
            - POSTGRES_DB=app_db
            - POSTGRES_USER=app_user
            - POSTGRES_PASSWORD=changeme
        restart: always

################################################################################
# redis
################################################################################

    redis:
        image: redis:3.0
        restart: always

################################################################################
# elasticsearch
################################################################################

    elasticsearch:
        image: elasticsearch:2.3
        restart: always

################################################################################
# esite app
################################################################################

    app:
        build: .
        environment:
            - DJANGO_SECRET_KEY=changeme
            - DATABASE_URL=postgres://app_user:changeme@db/app_db
            - CACHE_URL=redis://redis
            - ELASTICSEARCH_ENDPOINT=elasticsearch
        links:
            - db:db
            - redis:redis
            - elasticsearch:elasticsearch
        ports:
            - 50000:8000/tcp
        depends_on:
            - db
            - redis
            - elasticsearch
        restart: always
